"""init_analytics_schema

Revision ID: 6f1c5ca979fe
Revises: 
Create Date: 2026-01-09 04:18:11.410119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1c5ca979fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_carbon_metrics_created_at'), 'carbon_metrics', ['created_at'], unique=False)
    op.create_foreign_key(None, 'carbon_metrics', 'queries', ['query_id'], ['id'])
    op.create_foreign_key(None, 'model_responses', 'queries', ['query_id'], ['id'])
    op.add_column('queries', sa.Column('query_hash', sa.String(length=64), nullable=False))
    op.add_column('queries', sa.Column('complexity', sa.String(length=20), nullable=True))
    op.add_column('queries', sa.Column('intent', sa.String(length=50), nullable=True))
    op.add_column('queries', sa.Column('urgency', sa.String(length=20), nullable=True))
    op.add_column('queries', sa.Column('domain', sa.String(length=50), nullable=True))
    op.add_column('queries', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.add_column('queries', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_queries_query_hash'), 'queries', ['query_hash'], unique=True)
    op.create_index(op.f('ix_queries_session_id'), 'queries', ['session_id'], unique=False)
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    op.drop_column('queries', 'query_type')
    op.drop_column('queries', 'complexity_score')
    op.create_foreign_key(None, 'rl_feedback', 'queries', ['query_id'], ['id'])
    op.create_foreign_key(None, 'rl_feedback', 'routing_decisions', ['routing_decision_id'], ['id'])
    op.create_foreign_key(None, 'routing_decisions', 'queries', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routing_decisions', type_='foreignkey')
    op.drop_constraint(None, 'rl_feedback', type_='foreignkey')
    op.drop_constraint(None, 'rl_feedback', type_='foreignkey')
    op.add_column('queries', sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('query_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_session_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_query_hash'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_column('queries', 'session_id')
    op.drop_column('queries', 'user_id')
    op.drop_column('queries', 'domain')
    op.drop_column('queries', 'urgency')
    op.drop_column('queries', 'intent')
    op.drop_column('queries', 'complexity')
    op.drop_column('queries', 'query_hash')
    op.drop_constraint(None, 'model_responses', type_='foreignkey')
    op.drop_constraint(None, 'carbon_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_carbon_metrics_created_at'), table_name='carbon_metrics')
    # ### end Alembic commands ###
